spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

rabbitmq:
  queue:
    name: ${rabbitmq.q.name}
  exchange:
    name: ${rabbitmq.e.name}
  routing:
    key: ${rabbitmq.r.key}

cloud:
  aws:
    credentials:
      accessKey: ${aws_accessKey}
      secretKey: ${aws_secretKey}
    region:
      static: ${aws_region}
    stack:
      auto: ${aws_auto}
    s3:
      bucket: ${s3_bucket}

board:
  image:
    path: board

memo:
  image:
    path: memo

jwt:
  secret: ${jwt_secret}
  expiration: ${jwt_expiration}