spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
rabbitmq:
  queue:
    name: ${rabbitmq.queue.name}
  exchage:
    name: ${rabbitmq.exchange.name}
  routing:
    key: ${rabbitmq.routing.key}
  # Swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
cloud:
  aws:
    credentials:
      accessKey: ${cloud.aws.credentials.accessKey}
      secretKey: ${cloud.aws.credentials.secretKey}
    region:
      static: ${cloud.aws.region.static}
    stack:
      auto: ${cloud.aws.stack.auto}
    s3:
      bucket: ${cloud.aws.s3.bucket}

board:
  image:
    path: board